name: Looker Content Validation via API

on:
  workflow_dispatch:
    inputs:
        branch:
          description: 'Project'
          required: true
          default: 'sample_thelook_ecommerce'
        folders:
          description: 'Folders'
          required: true
          default: '1'
  # workflow_run:
  #   workflows: ["Merge Master to UAT"]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install --upgrade looker_sdk

      - name: Run Looker Content Validation
        env:
          LOOKERSDK_BASE_URL: ${{ secrets.UAT_LOOKER_BASE_URL }}
          LOOKERSDK_CLIENT_ID: ${{ secrets.UAT_CLIENT_ID }}
          LOOKERSDK_CLIENT_SECRET: ${{ secrets.UAT_CLIENT_SECRET }}
        run: |
          python <<EOF
          import looker_sdk
          from looker_sdk import models40 as mdls
  
          sdk = looker_sdk.init40()

          project_id = '${{ github.event.inputs.project_id }}'
          folder_ids = '${{ github.event.inputs.folders }}'
          
          try:
              results = sdk.content_validation(project_names=mdls.DelimSequence([project_id]), space_ids=mdls.DelimSequence([folder_ids]))
              print(f"Looker Content Validated Successfully in project: {project_id} and folders: {folder_ids}")
              print("==== Looks Validated ====")
              print(results.total_looks_validated)
              print()
          
              print("==== Dashboard Tiles Validated ====")
              print(results.total_dashboard_elements_validated)
              print()
          
              print("==== Explores Validated ====")
              print(results.total_explores_validated)
              print()
          
              print("==== Number of Errors ====")
              num_errors = len(results.content_with_errors)
              print(num_errors)
              print()
              if num_errors > 0:
                print(f"Validation Errors detected: {results.content_with_errors}")
                exit(1)
          
          except looker_sdk.error.SDKError as e:
              print(f"Validation Errors detected: {e}")
              exit(1)
          EOF
