name: Create Release Tag and Branch

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Fetch Tags
        run: git fetch --tags

      - name: Determine next release version
        id: version
        run: |
          TAGS=$(git tag -l | sort -V | tail -n 1)
          if [[ -z "$TAGS" ]]; then
            NEW_TAG="1.0.0"
          else
            VERSION_PARTS=(${TAGS//./ })
            PATCH_VERSION=$(( ${VERSION_PARTS} + 1 ))
            NEW_TAG="${VERSION_PARTS}.${VERSION_PARTS}.${PATCH_VERSION}"
          fi
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create Tag
        run: |
          git tag -a ${{ steps.version.outputs.new_tag }} -m "Release ${{ steps.version.outputs.new_tag }}"
          git push origin ${{ steps.version.outputs.new_tag }}

      - name: Create release branch
        run: |
          git checkout -b "release/${{ steps.version.outputs.new_tag }}"

      - name: Push release branch
        run: |
          git push origin "release/${{ steps.version.outputs.new_tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
