name: Deploy Looker Changes to UAT

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install looker_sdk

      - name: Deploy to UAT Looker
        env:
          UAT_LOOKER_BASE_URL: ${{ secrets.UAT_LOOKER_BASE_URL }}
          UAT_LOOKER_CLIENT_ID: ${{ secrets.UAT_LOOKER_CLIENT_ID }}
          UAT_LOOKER_CLIENT_SECRET: ${{ secrets.UAT_LOOKER_CLIENT_SECRET }}
          UAT_LOOKER_PROJECT_ID: ${{ secrets.UAT_LOOKER_PROJECT_ID }}
          GIT_BRANCH: uat # or main, depending on your production branch
        run: |
          python <<EOF
          import looker_sdk
          from looker_sdk import models
          import os

          sdk = looker_sdk.init40(
              client_id=os.environ["UAT_LOOKER_CLIENT_ID"],
              client_secret=os.environ["UAT_LOOKER_CLIENT_SECRET"],
              base_url=os.environ["UAT_LOOKER_BASE_URL"],
          )

          project_id = os.environ["UAT_LOOKER_PROJECT_ID"]
          git_branch = os.environ["GIT_BRANCH"]

          try:
              sdk.update_git_branch(project_id=project_id, name=git_branch, deploy_ref=True)
              print(f"Successfully deployed branch '{git_branch}' to production in project: {project_id}")

          except looker_sdk.error.SDKError as e:
              print(f"Error deploying branch: {e}")
              exit(1)
          EOF
