name: Merge Master to UAT

on:
  push:
    branches:
      - master  
permissions:
  contents: write  # Explicitly grant write access to repository contents

jobs:
  merge_master_to_uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Fetch master branch
        run: git fetch origin master

      - name: Merge master into uat
        run: |
          git checkout uat
          git pull origin uat
          git merge origin/master --no-edit
          git push origin uat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
