name: Merge Main to UAT

on:
  push:
    branches:
      - master

jobs:
  merge_main_to_uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for accurate branch and tag retrieval

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Merge main into uat
        run: |
          git checkout uat
          git pull origin uat
          git merge origin/main --no-edit # Use --no-edit to avoid interactive commit message prompts
          git push origin uat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure you have a GITHUB_TOKEN secret.
