
name: Spectacles Validation
#


on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  
  workflow_dispatch:
    inputs:
      message:
        description: 'Branch'
        required: true
        default: 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      # Runs a single command using the runners shell
      - name: Install Spectacles
        run: pip install spectacles

      # Runs a single command using the runners shell
      - name: Install Looker SDK
        run: pip install looker_sdk

      - name: Spectacles SQL Checks
        run: spectacles sql --base-url https://0a008a8e-ad98-4f2e-95c4-99bcdc1ff974.looker.app --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --port 443 --project thelook --explores ecommerceSA/order_items_local --branch ${{ github.event.inputs.message }}
      
      - name: Spectacles Validation Checks - Dev instance
        run: spectacles content --base-url https://0a008a8e-ad98-4f2e-95c4-99bcdc1ff974.looker.app --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --port 443 --project thelook --explores ecommerceSA/order_items_local --branch ${{ github.event.inputs.message }}
      
      - name: Spectacles Validation Checks - UAT instance
        run: spectacles content --base-url https://083dec7c-443d-4142-9e40-940cc101631a.looker.app --client-id ${{ secrets.UAT_CLIENT_ID }} --client-secret ${{ secrets.UAT_CLIENT_SECRET }} --port 443 --project thelook --folder 5 --branch ${{ github.event.inputs.message }}


